sudo: required

addons:
  chrome: stable

matrix:
  include:
  - os: linux
    language: python
    python: 2.7
    services:
    - rabbitmq
    - memcached
    - postgresql
  - os: linux
    language: python
    python: 3.5
    services:
    - rabbitmq
    - memcached
    - postgresql
  - os: osx
  allow_failures:
  - os: linux
    language: python
    python: 3.5

# command to run tests
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew outdated pyenv || brew upgrade pyenv;
        brew install pyenv-virtualenv;
        pyenv versions;
        pyenv install 3.5.0;
        export PYENV_VERSION=3.5.0;
        export PATH="/Users/travis/.pyenv/shims:${PATH}";
        pyenv versions;
        pyenv-virtualenv venv;
        source venv/bin/activate;
        pyenv versions;
        python -V;
        python3 -V;
        pip -V;
        pip3 -V;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        which python;
        which pip;
        which python2;
        which pip2;
        python --version;
        pip --version;
        python2 --version;
        pip2 --version;
        sudo which python;
        sudo which pip;
        sudo which python2;
        sudo which pip2;
        sudo python --version;
        sudo pip --version;
        sudo python2 --version;
        sudo pip2 --version;
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        which python;
        which pip;
        which python3;
        which pip3;
        python --version;
        pip --version;
        python3 --version;
        pip3 --version;
        sudo which python;
        sudo which pip;
        sudo which python3;
        sudo which pip3;
        sudo python --version;
        sudo pip --version;
        sudo python3 --version;
        sudo pip3 --version;
    fi
